

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v4
      - name: build image
        run: docker build -t kayitesimarieange3h-del/resume .
        
      - name: push image
        run: |
              docker login -u kayitesimarieange3h-del -p ${{secrets.REGISTRY_PASS}}
              docker push kayitesimarieange3h-del/resume

          